
import './globals.css'
import { Raleway } from 'next/font/google'
import NavBar from "../components/navigation/navigation"
import { Analytics } from '@vercel/analytics/react';

const raleway = Raleway({ 
  weight: ['400', '500', '600', '700'],
  subsets: ['latin']
})

const hideButton = false

export const metadata = {
  title: 'WanderAI',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel='icon' href='/favicon.ico'/>
      </head>
      <body className={raleway.className}>
        <NavBar hideButton={hideButton}/>
        {children}
        <Analytics/>
      </body>
    </html>
  )
}
